// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSession(arg1) {
  return window['go']['services']['AuthService']['CheckSession'](arg1);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['services']['AuthService']['Login'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['services']['AuthService']['Logout']();
}

export function RestoreSession() {
  return window['go']['services']['AuthService']['RestoreSession']();
}
