// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CheckSession(arg1:context.Context):Promise<boolean>;

export function Login(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function Logout():Promise<void>;

export function RestoreSession():Promise<string>;
