// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddReaction(arg1, arg2, arg3) {
  return window['go']['services']['ChatService']['AddReaction'](arg1, arg2, arg3);
}

export function DeleteMessage(arg1, arg2) {
  return window['go']['services']['ChatService']['DeleteMessage'](arg1, arg2);
}

export function GetConvoForMembers(arg1) {
  return window['go']['services']['ChatService']['GetConvoForMembers'](arg1);
}

export function GetMessages(arg1, arg2) {
  return window['go']['services']['ChatService']['GetMessages'](arg1, arg2);
}

export function GetUnreadCount() {
  return window['go']['services']['ChatService']['GetUnreadCount']();
}

export function LeaveConvo(arg1) {
  return window['go']['services']['ChatService']['LeaveConvo'](arg1);
}

export function ListConvos(arg1) {
  return window['go']['services']['ChatService']['ListConvos'](arg1);
}

export function MuteConvo(arg1) {
  return window['go']['services']['ChatService']['MuteConvo'](arg1);
}

export function RemoveReaction(arg1, arg2, arg3) {
  return window['go']['services']['ChatService']['RemoveReaction'](arg1, arg2, arg3);
}

export function SendMessage(arg1, arg2) {
  return window['go']['services']['ChatService']['SendMessage'](arg1, arg2);
}

export function SendMessageWithGif(arg1, arg2, arg3) {
  return window['go']['services']['ChatService']['SendMessageWithGif'](arg1, arg2, arg3);
}

export function SendReply(arg1, arg2, arg3, arg4) {
  return window['go']['services']['ChatService']['SendReply'](arg1, arg2, arg3, arg4);
}

export function UnmuteConvo(arg1) {
  return window['go']['services']['ChatService']['UnmuteConvo'](arg1);
}

export function UpdateReadStatus(arg1, arg2) {
  return window['go']['services']['ChatService']['UpdateReadStatus'](arg1, arg2);
}
