// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function DeleteMessage(arg1:string,arg2:string):Promise<void>;

export function GetConvoForMembers(arg1:Array<string>):Promise<services.ChatConvoDTO>;

export function GetMessages(arg1:string,arg2:string):Promise<services.ChatMessagesDTO>;

export function GetUnreadCount():Promise<number>;

export function LeaveConvo(arg1:string):Promise<void>;

export function ListConvos(arg1:string):Promise<Array<services.ChatConvoDTO>>;

export function MuteConvo(arg1:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SendMessageWithGif(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UnmuteConvo(arg1:string):Promise<void>;

export function UpdateReadStatus(arg1:string,arg2:string):Promise<void>;
