// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {bsky} from '../models';

export function GetActorLikes(arg1:string,arg2:string,arg3:number):Promise<services.FeedDTO>;

export function GetAuthorFeed(arg1:string,arg2:string,arg3:number,arg4:string):Promise<services.FeedDTO>;

export function GetBookmarks(arg1:string,arg2:number):Promise<services.FeedDTO>;

export function GetCustomFeed(arg1:string,arg2:string,arg3:number):Promise<services.FeedDTO>;

export function GetLikes(arg1:string,arg2:string,arg3:string):Promise<services.ProfileListDTO>;

export function GetListFeed(arg1:string,arg2:string,arg3:number):Promise<services.FeedDTO>;

export function GetPopularFeedGenerators(arg1:string,arg2:string):Promise<services.FeedGeneratorResponseDTO>;

export function GetPostThread(arg1:string,arg2:number):Promise<services.FeedDTO>;

export function GetPosts(arg1:Array<string>):Promise<services.FeedDTO>;

export function GetQuotes(arg1:string,arg2:string,arg3:string):Promise<services.FeedDTO>;

export function GetRepostedBy(arg1:string,arg2:string,arg3:string):Promise<services.ProfileListDTO>;

export function GetSavedFeeds():Promise<Array<services.SavedFeedDTO>>;

export function GetThread(arg1:string,arg2:number):Promise<bsky.FeedGetPostThread_Output>;

export function GetTimeline(arg1:string,arg2:number):Promise<services.FeedDTO>;
