// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActorLikes(arg1, arg2, arg3) {
  return window['go']['services']['FeedService']['GetActorLikes'](arg1, arg2, arg3);
}

export function GetAuthorFeed(arg1, arg2, arg3, arg4) {
  return window['go']['services']['FeedService']['GetAuthorFeed'](arg1, arg2, arg3, arg4);
}

export function GetBookmarks(arg1, arg2) {
  return window['go']['services']['FeedService']['GetBookmarks'](arg1, arg2);
}

export function GetCustomFeed(arg1, arg2, arg3) {
  return window['go']['services']['FeedService']['GetCustomFeed'](arg1, arg2, arg3);
}

export function GetLikes(arg1, arg2, arg3) {
  return window['go']['services']['FeedService']['GetLikes'](arg1, arg2, arg3);
}

export function GetListFeed(arg1, arg2, arg3) {
  return window['go']['services']['FeedService']['GetListFeed'](arg1, arg2, arg3);
}

export function GetPopularFeedGenerators(arg1, arg2) {
  return window['go']['services']['FeedService']['GetPopularFeedGenerators'](arg1, arg2);
}

export function GetPostThread(arg1, arg2) {
  return window['go']['services']['FeedService']['GetPostThread'](arg1, arg2);
}

export function GetPosts(arg1) {
  return window['go']['services']['FeedService']['GetPosts'](arg1);
}

export function GetQuotes(arg1, arg2, arg3) {
  return window['go']['services']['FeedService']['GetQuotes'](arg1, arg2, arg3);
}

export function GetRepostedBy(arg1, arg2, arg3) {
  return window['go']['services']['FeedService']['GetRepostedBy'](arg1, arg2, arg3);
}

export function GetSavedFeeds() {
  return window['go']['services']['FeedService']['GetSavedFeeds']();
}

export function GetThread(arg1, arg2) {
  return window['go']['services']['FeedService']['GetThread'](arg1, arg2);
}

export function GetTimeline(arg1, arg2) {
  return window['go']['services']['FeedService']['GetTimeline'](arg1, arg2);
}
