// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockActor(arg1) {
  return window['go']['services']['ModerationService']['BlockActor'](arg1);
}

export function GetBlocks(arg1) {
  return window['go']['services']['ModerationService']['GetBlocks'](arg1);
}

export function GetMuteScope(arg1) {
  return window['go']['services']['ModerationService']['GetMuteScope'](arg1);
}

export function GetMutes(arg1) {
  return window['go']['services']['ModerationService']['GetMutes'](arg1);
}

export function MuteActor(arg1) {
  return window['go']['services']['ModerationService']['MuteActor'](arg1);
}

export function MuteActorScoped(arg1, arg2, arg3) {
  return window['go']['services']['ModerationService']['MuteActorScoped'](arg1, arg2, arg3);
}

export function MuteThread(arg1) {
  return window['go']['services']['ModerationService']['MuteThread'](arg1);
}

export function ReportAccount(arg1, arg2, arg3) {
  return window['go']['services']['ModerationService']['ReportAccount'](arg1, arg2, arg3);
}

export function ReportPost(arg1, arg2, arg3, arg4) {
  return window['go']['services']['ModerationService']['ReportPost'](arg1, arg2, arg3, arg4);
}

export function UnblockActor(arg1) {
  return window['go']['services']['ModerationService']['UnblockActor'](arg1);
}

export function UnmuteActor(arg1) {
  return window['go']['services']['ModerationService']['UnmuteActor'](arg1);
}

export function UnmuteThread(arg1) {
  return window['go']['services']['ModerationService']['UnmuteThread'](arg1);
}
