// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function BlockActor(arg1:string):Promise<void>;

export function GetBlocks(arg1:string):Promise<services.ProfileListDTO>;

export function GetMutes(arg1:string):Promise<services.ProfileListDTO>;

export function MuteActor(arg1:string):Promise<void>;

export function MuteThread(arg1:string):Promise<void>;

export function ReportAccount(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReportPost(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UnblockActor(arg1:string):Promise<void>;

export function UnmuteActor(arg1:string):Promise<void>;

export function UnmuteThread(arg1:string):Promise<void>;
