// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function GetNotifications(arg1:string):Promise<services.NotificationListDTO>;

export function GetUnreadCount():Promise<number>;

export function PutActivitySubscription(arg1:string,arg2:boolean,arg3:boolean):Promise<services.ActivitySubscriptionDTO>;

export function UpdateSeen(arg1:string):Promise<void>;
