// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNotifications(arg1) {
  return window['go']['services']['NotificationsService']['GetNotifications'](arg1);
}

export function GetUnreadCount() {
  return window['go']['services']['NotificationsService']['GetUnreadCount']();
}

export function UpdateSeen(arg1) {
  return window['go']['services']['NotificationsService']['UpdateSeen'](arg1);
}
