// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNotificationPreferences() {
  return window['go']['services']['NotificationsService']['GetNotificationPreferences']();
}

export function GetNotifications(arg1) {
  return window['go']['services']['NotificationsService']['GetNotifications'](arg1);
}

export function GetUnreadCount() {
  return window['go']['services']['NotificationsService']['GetUnreadCount']();
}

export function PutActivitySubscription(arg1, arg2, arg3) {
  return window['go']['services']['NotificationsService']['PutActivitySubscription'](arg1, arg2, arg3);
}

export function PutNotificationPreferences(arg1) {
  return window['go']['services']['NotificationsService']['PutNotificationPreferences'](arg1);
}

export function UpdateSeen(arg1) {
  return window['go']['services']['NotificationsService']['UpdateSeen'](arg1);
}
