// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BookmarkPost(arg1, arg2) {
  return window['go']['services']['PostBuilderService']['BookmarkPost'](arg1, arg2);
}

export function CheckVideoStatus(arg1) {
  return window['go']['services']['PostBuilderService']['CheckVideoStatus'](arg1);
}

export function CreatePost(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['services']['PostBuilderService']['CreatePost'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function DeletePost(arg1) {
  return window['go']['services']['PostBuilderService']['DeletePost'](arg1);
}

export function DeleteRepost(arg1) {
  return window['go']['services']['PostBuilderService']['DeleteRepost'](arg1);
}

export function FetchLinkCard(arg1) {
  return window['go']['services']['PostBuilderService']['FetchLinkCard'](arg1);
}

export function HideReply(arg1, arg2) {
  return window['go']['services']['PostBuilderService']['HideReply'](arg1, arg2);
}

export function LikePost(arg1, arg2) {
  return window['go']['services']['PostBuilderService']['LikePost'](arg1, arg2);
}

export function QuotePost(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['services']['PostBuilderService']['QuotePost'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function Repost(arg1, arg2) {
  return window['go']['services']['PostBuilderService']['Repost'](arg1, arg2);
}

export function UnbookmarkPost(arg1, arg2) {
  return window['go']['services']['PostBuilderService']['UnbookmarkPost'](arg1, arg2);
}

export function UnlikePost(arg1) {
  return window['go']['services']['PostBuilderService']['UnlikePost'](arg1);
}
