// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function BookmarkPost(arg1:string,arg2:string):Promise<string>;

export function CheckVideoStatus(arg1:string):Promise<services.VideoJobStatusDTO>;

export function CreatePost(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>,arg7:Array<string>,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string,arg13:string,arg14:number,arg15:number,arg16:Array<string>):Promise<services.PostRefDTO>;

export function DeletePost(arg1:string):Promise<void>;

export function DeleteRepost(arg1:string):Promise<void>;

export function FetchLinkCard(arg1:string):Promise<services.ExternalEmbedDTO>;

export function HideReply(arg1:string,arg2:string):Promise<void>;

export function LikePost(arg1:string,arg2:string):Promise<string>;

export function QuotePost(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:Array<string>,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:number,arg12:number,arg13:Array<string>):Promise<services.PostRefDTO>;

export function Repost(arg1:string,arg2:string):Promise<string>;

export function UnbookmarkPost(arg1:string,arg2:string):Promise<void>;

export function UnlikePost(arg1:string):Promise<void>;
