// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function SearchPosts(arg1:services.PostSearchFilter):Promise<services.SearchDTO>;

export function SearchProfiles(arg1:string,arg2:string):Promise<services.ProfileListDTO>;

export function SearchProfilesTypeahead(arg1:string):Promise<services.ProfileListDTO>;
