// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchPosts(arg1) {
  return window['go']['services']['SearchService']['SearchPosts'](arg1);
}

export function SearchProfiles(arg1, arg2) {
  return window['go']['services']['SearchService']['SearchProfiles'](arg1, arg2);
}

export function SearchProfilesTypeahead(arg1) {
  return window['go']['services']['SearchService']['SearchProfilesTypeahead'](arg1);
}
