// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSelfLabel(arg1) {
  return window['go']['services']['SocialService']['AddSelfLabel'](arg1);
}

export function AddUserToList(arg1, arg2) {
  return window['go']['services']['SocialService']['AddUserToList'](arg1, arg2);
}

export function BlockList(arg1) {
  return window['go']['services']['SocialService']['BlockList'](arg1);
}

export function CreateList(arg1, arg2, arg3) {
  return window['go']['services']['SocialService']['CreateList'](arg1, arg2, arg3);
}

export function CreateStarterPack(arg1, arg2, arg3) {
  return window['go']['services']['SocialService']['CreateStarterPack'](arg1, arg2, arg3);
}

export function DeleteList(arg1) {
  return window['go']['services']['SocialService']['DeleteList'](arg1);
}

export function DeleteStarterPack(arg1) {
  return window['go']['services']['SocialService']['DeleteStarterPack'](arg1);
}

export function EditList(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SocialService']['EditList'](arg1, arg2, arg3, arg4);
}

export function Follow(arg1) {
  return window['go']['services']['SocialService']['Follow'](arg1);
}

export function FollowAllInList(arg1) {
  return window['go']['services']['SocialService']['FollowAllInList'](arg1);
}

export function GetActorLists(arg1, arg2) {
  return window['go']['services']['SocialService']['GetActorLists'](arg1, arg2);
}

export function GetActorStarterPacks(arg1, arg2) {
  return window['go']['services']['SocialService']['GetActorStarterPacks'](arg1, arg2);
}

export function GetFollowers(arg1, arg2) {
  return window['go']['services']['SocialService']['GetFollowers'](arg1, arg2);
}

export function GetFollows(arg1, arg2) {
  return window['go']['services']['SocialService']['GetFollows'](arg1, arg2);
}

export function GetLabelerServices(arg1) {
  return window['go']['services']['SocialService']['GetLabelerServices'](arg1);
}

export function GetListMembers(arg1, arg2) {
  return window['go']['services']['SocialService']['GetListMembers'](arg1, arg2);
}

export function GetPreferences() {
  return window['go']['services']['SocialService']['GetPreferences']();
}

export function GetProfile(arg1) {
  return window['go']['services']['SocialService']['GetProfile'](arg1);
}

export function GetSelfLabels() {
  return window['go']['services']['SocialService']['GetSelfLabels']();
}

export function GetSubscribedLabelerDIDs() {
  return window['go']['services']['SocialService']['GetSubscribedLabelerDIDs']();
}

export function GetSubscribedLabelers() {
  return window['go']['services']['SocialService']['GetSubscribedLabelers']();
}

export function GetSuggestedFollows() {
  return window['go']['services']['SocialService']['GetSuggestedFollows']();
}

export function MuteList(arg1) {
  return window['go']['services']['SocialService']['MuteList'](arg1);
}

export function PinPost(arg1, arg2) {
  return window['go']['services']['SocialService']['PinPost'](arg1, arg2);
}

export function RemoveSelfLabel(arg1) {
  return window['go']['services']['SocialService']['RemoveSelfLabel'](arg1);
}

export function RemoveUserFromList(arg1) {
  return window['go']['services']['SocialService']['RemoveUserFromList'](arg1);
}

export function SubscribeLabeler(arg1) {
  return window['go']['services']['SocialService']['SubscribeLabeler'](arg1);
}

export function SubscribeList(arg1) {
  return window['go']['services']['SocialService']['SubscribeList'](arg1);
}

export function UnblockList(arg1) {
  return window['go']['services']['SocialService']['UnblockList'](arg1);
}

export function Unfollow(arg1) {
  return window['go']['services']['SocialService']['Unfollow'](arg1);
}

export function UnmuteList(arg1) {
  return window['go']['services']['SocialService']['UnmuteList'](arg1);
}

export function UnpinPost() {
  return window['go']['services']['SocialService']['UnpinPost']();
}

export function UnsubscribeLabeler(arg1) {
  return window['go']['services']['SocialService']['UnsubscribeLabeler'](arg1);
}

export function UnsubscribeList(arg1) {
  return window['go']['services']['SocialService']['UnsubscribeList'](arg1);
}

export function UpdateAdultContentEnabled(arg1) {
  return window['go']['services']['SocialService']['UpdateAdultContentEnabled'](arg1);
}

export function UpdateAllPreferences(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SocialService']['UpdateAllPreferences'](arg1, arg2, arg3, arg4);
}

export function UpdateContentFilters(arg1) {
  return window['go']['services']['SocialService']['UpdateContentFilters'](arg1);
}

export function UpdateMutedWords(arg1) {
  return window['go']['services']['SocialService']['UpdateMutedWords'](arg1);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['services']['SocialService']['UpdateProfile'](arg1, arg2);
}

export function UpdateSavedFeeds(arg1, arg2) {
  return window['go']['services']['SocialService']['UpdateSavedFeeds'](arg1, arg2);
}

export function UpdateThreadPreferences(arg1, arg2) {
  return window['go']['services']['SocialService']['UpdateThreadPreferences'](arg1, arg2);
}

export function UploadProfileAvatar(arg1) {
  return window['go']['services']['SocialService']['UploadProfileAvatar'](arg1);
}

export function UploadProfileBanner(arg1) {
  return window['go']['services']['SocialService']['UploadProfileBanner'](arg1);
}
