// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function AddSelfLabel(arg1:string):Promise<void>;

export function AddUserToList(arg1:string,arg2:string):Promise<string>;

export function BlockList(arg1:string):Promise<void>;

export function CreateList(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateStarterPack(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteList(arg1:string):Promise<void>;

export function DeleteStarterPack(arg1:string):Promise<void>;

export function EditList(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function Follow(arg1:string):Promise<void>;

export function FollowAllInList(arg1:string):Promise<number>;

export function GetActorLists(arg1:string,arg2:string):Promise<services.ListResponseDTO>;

export function GetActorStarterPacks(arg1:string,arg2:string):Promise<services.StarterPackResponseDTO>;

export function GetFollowers(arg1:string,arg2:string):Promise<services.ProfileListDTO>;

export function GetFollows(arg1:string,arg2:string):Promise<services.ProfileListDTO>;

export function GetListMembers(arg1:string,arg2:string):Promise<services.ProfileListDTO>;

export function GetPreferences():Promise<services.PreferencesDTO>;

export function GetProfile(arg1:string):Promise<services.ProfileDTO>;

export function GetSelfLabels():Promise<Array<string>>;

export function GetSuggestedFollows():Promise<services.ProfileListDTO>;

export function MuteList(arg1:string):Promise<void>;

export function PinPost(arg1:string,arg2:string):Promise<void>;

export function RemoveSelfLabel(arg1:string):Promise<void>;

export function RemoveUserFromList(arg1:string):Promise<void>;

export function SubscribeList(arg1:string):Promise<void>;

export function UnblockList(arg1:string):Promise<void>;

export function Unfollow(arg1:string):Promise<void>;

export function UnmuteList(arg1:string):Promise<void>;

export function UnpinPost():Promise<void>;

export function UnsubscribeList(arg1:string):Promise<void>;

export function UpdateAdultContentEnabled(arg1:boolean):Promise<void>;

export function UpdateAllPreferences(arg1:string,arg2:boolean,arg3:Array<string>,arg4:Array<services.ContentFilterDTO>):Promise<void>;

export function UpdateContentFilters(arg1:Array<services.ContentFilterDTO>):Promise<void>;

export function UpdateMutedWords(arg1:Array<string>):Promise<void>;

export function UpdateProfile(arg1:string,arg2:string):Promise<void>;

export function UpdateSavedFeeds(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function UpdateThreadPreferences(arg1:string,arg2:boolean):Promise<void>;

export function UploadProfileAvatar(arg1:string):Promise<void>;

export function UploadProfileBanner(arg1:string):Promise<void>;
